name: CREATE TABLE - prymal_order_log
run-name: ${{ github.actor }} - CREATE TABLE - prymal_order_log
on: 
  push:
    paths:
      - '**/create_table/**'
      - '**/.github/workflows/create_table.yml'

jobs:
  create_table:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls create_table
      - name: Print wd
        run: |
          pwd
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r create_table/requirements.txt
    
      - name: CREATE TABLE - prymal_order_log
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          PRYMAL_S3_ANALYTICS: ${{ secrets.PRYMAL_S3_ANALYTICS }}
        run: python create_table/create_table.py 

      - run: echo "Job status - ${{ job.status }}."
