name: Prymal Order Log
run-name: ${{ github.actor }} - Prymal Order Log
on: 
  push:
    paths:
      - '**/scripts/pipeline.py'
      - '**/workflows/pipeline_workflow.yml'
  schedule:
    - cron: '0 10 * * *'  # Runs at 10 AM every day (UTC)
jobs:
  pipeline_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Generate Order Log
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_PRYMAL_ANALYTICS: ${{ secrets.S3_PRYMAL_ANALYTICS }}
        run: python scripts/pipeline.py 


      - run: echo "Job status - ${{ job.status }}."
